version: '3'
services:
  express:
    image: node:alpine
    container_name: express-loc
    volumes:
      - ./node_modules:/node_modules
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./public:/public
      - ./src:/src
    command: sh -c "yarn build && yarn start"
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PORT=80
      - VIRTUAL_HOST=loc.arbona.dev
      - LETSENCRYPT_HOST=loc.arbona.dev
      - LETSENCRYPT_EMAIL=arbona.robin@gmail.com
    networks:
      - "net"

  db:
    image: postgres:13-alpine
    container_name: express-loc-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - "net"

networks:
  net:
    external: true